//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Move.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Move.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseMenuItem_Text {
            get {
                return ResourceManager.GetString("CloseMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the application.
        /// </summary>
        internal static string CloseMenuItem_ToolTipText {
            get {
                return ResourceManager.GetString("CloseMenuItem_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balloon ToolTip.
        /// </summary>
        internal static string EnableBalloonToolTip_Text {
            get {
                return ResourceManager.GetString("EnableBalloonToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the timer expires, a tooltip will appear for a short period and will reset the timer itself on closure.
        /// </summary>
        internal static string EnableBalloonToolTip_TooltipText {
            get {
                return ResourceManager.GetString("EnableBalloonToolTip_TooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Icon.
        /// </summary>
        internal static string EnableFlashIcon_Text {
            get {
                return ResourceManager.GetString("EnableFlashIcon_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the timer expires, the taskbar icon will flash until reset.
        /// </summary>
        internal static string EnableFlashIcon_ToolTipText {
            get {
                return ResourceManager.GetString("EnableFlashIcon_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Machine.
        /// </summary>
        internal static string EnableMachineLock_Text {
            get {
                return ResourceManager.GetString("EnableMachineLock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the timer expires, the machine will be locked and require unlocking.
        /// </summary>
        internal static string EnableMachineLock_ToolTipText {
            get {
                return ResourceManager.GetString("EnableMachineLock_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Screen.
        /// </summary>
        internal static string EnableScreenFlash_Text {
            get {
                return ResourceManager.GetString("EnableScreenFlash_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the timer expires, the screen will flash until reset.
        /// </summary>
        internal static string EnableScreenFlash_ToolTipText {
            get {
                return ResourceManager.GetString("EnableScreenFlash_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Beep.
        /// </summary>
        internal static string EnableSystemBeep_Text {
            get {
                return ResourceManager.GetString("EnableSystemBeep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the timer expires, a sound will be output until reset.
        /// </summary>
        internal static string EnableSystemBeep_ToolTipText {
            get {
                return ResourceManager.GetString("EnableSystemBeep_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconBlank {
            get {
                object obj = ResourceManager.GetObject("IconBlank", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconPaused {
            get {
                object obj = ResourceManager.GetObject("IconPaused", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string PauseMenuItem_TextPause {
            get {
                return ResourceManager.GetString("PauseMenuItem_TextPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string PauseMenuItem_TextResume {
            get {
                return ResourceManager.GetString("PauseMenuItem_TextResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauses the timer to the specified interval.
        /// </summary>
        internal static string PauseMenuItem_ToolTipText {
            get {
                return ResourceManager.GetString("PauseMenuItem_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ResetMenuItem_Text {
            get {
                return ResourceManager.GetString("ResetMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the timer to the specified interval.
        /// </summary>
        internal static string ResetMenuItem_ToolTipText {
            get {
                return ResourceManager.GetString("ResetMenuItem_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenuItem_Text {
            get {
                return ResourceManager.GetString("SettingsMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the settings dialog to allow behaviour customization.
        /// </summary>
        internal static string SettingsMenuItem_ToolTipText {
            get {
                return ResourceManager.GetString("SettingsMenuItem_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the timer interval.
        /// </summary>
        internal static string TimerInterval_ToolTipText {
            get {
                return ResourceManager.GetString("TimerInterval_ToolTipText", resourceCulture);
            }
        }
    }
}
