//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Move.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int MoveIntervalMinutes {
            get {
                return ((int)(this["MoveIntervalMinutes"]));
            }
            set {
                this["MoveIntervalMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActionFlashIconEnabled {
            get {
                return ((bool)(this["ActionFlashIconEnabled"]));
            }
            set {
                this["ActionFlashIconEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActionSystemBeepEnabled {
            get {
                return ((bool)(this["ActionSystemBeepEnabled"]));
            }
            set {
                this["ActionSystemBeepEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ActionBalloonTipEnabled {
            get {
                return ((bool)(this["ActionBalloonTipEnabled"]));
            }
            set {
                this["ActionBalloonTipEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActionFlashScreenEnabled {
            get {
                return ((bool)(this["ActionFlashScreenEnabled"]));
            }
            set {
                this["ActionFlashScreenEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ActionLockMachineEnabled {
            get {
                return ((bool)(this["ActionLockMachineEnabled"]));
            }
            set {
                this["ActionLockMachineEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ActionFlashIconSpeed {
            get {
                return ((int)(this["ActionFlashIconSpeed"]));
            }
            set {
                this["ActionFlashIconSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int ActionFlashScreenSpeed {
            get {
                return ((int)(this["ActionFlashScreenSpeed"]));
            }
            set {
                this["ActionFlashScreenSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double ActionFlashScreenOpacity {
            get {
                return ((double)(this["ActionFlashScreenOpacity"]));
            }
            set {
                this["ActionFlashScreenOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunOnStartupEnabled {
            get {
                return ((bool)(this["RunOnStartupEnabled"]));
            }
            set {
                this["RunOnStartupEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Random")]
        public string ActionFlashScreenBehaviour {
            get {
                return ((string)(this["ActionFlashScreenBehaviour"]));
            }
            set {
                this["ActionFlashScreenBehaviour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ActionFlashScreenColourCustom {
            get {
                return ((global::System.Drawing.Color)(this["ActionFlashScreenColourCustom"]));
            }
            set {
                this["ActionFlashScreenColourCustom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int ActionSystemBeepSpeed {
            get {
                return ((int)(this["ActionSystemBeepSpeed"]));
            }
            set {
                this["ActionSystemBeepSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Time to move!")]
        public string ActionBalloonTipText {
            get {
                return ((string)(this["ActionBalloonTipText"]));
            }
            set {
                this["ActionBalloonTipText"] = value;
            }
        }
    }
}
